{
 "title": "Spring Boot 3.x Statistics",
 "description": "Spring Boot Dashboard adapted from https://grafana.com/grafana/dashboards/10280-microservices-spring-boot-2-1/",
 "tags": [ "app" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_info,application)"
    }
   },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(jvm_info,namespace)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_info{application=\"$application\", namespace=\"$Namespace\"},instance)"
    }
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": {
     "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
    }
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
    }
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds * 1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds" }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes) * 100) / sum(jvm_memory_max_bytes)"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used_bytes) * 100) / sum(jvm_memory_max_bytes)"
    }
   ]
  },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "repeat": "memory_pool_heap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "__auto" },
    { "expr": "jvm_buffer_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count[$__rate_interval])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "System CPU Usage" }
   ]
  },
  { "title": "JVM Statistics - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "repeat": "memory_pool_heap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "Used" },
    { "expr": "jvm_memory_committed_bytes", "legendFormat": "Commited" },
    { "expr": "jvm_buffer_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jvm_threads_daemon_threads", "legendFormat": "Daemon" },
    { "expr": "jvm_threads_live_threads", "legendFormat": "Live" },
    { "expr": "jvm_threads_peak_threads", "legendFormat": "Peak" }
   ]
  },
  { "title": "JVM Statistics - GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "GC Stop the World Duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_sum[$__rate_interval])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "Database Connection Pool HikariCP  Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 }
  },
  {
   "title": "Connections Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hikaricp_connections" }
   ]
  },
  {
   "title": "Connection Timeout Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "hikaricp_connections_active", "legendFormat": "Active" },
    { "expr": "hikaricp_connections_idle", "legendFormat": "Idle" },
    { "expr": "hikaricp_connections_pending", "legendFormat": "Pending" }
   ]
  },
  {
   "title": "Connection Usage Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_sum / hikaricp_connections_usage_seconds_count",
     "legendFormat": "Usage Time"
    }
   ]
  },
  {
   "title": "Connection Acquire Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_sum / hikaricp_connections_acquire_seconds_count",
     "legendFormat": "Acquire Time"
    }
   ]
  },
  { "title": "HTTP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count[$__rate_interval])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum[$__rate_interval]) / irate(http_server_requests_seconds_count[$__rate_interval])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Logback Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "panels": [
    {
     "title": "INFO logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"info\", namespace=\"$Namespace\"}[$__rate_interval])",
       "legendFormat": "info",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "ERROR logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"error\", namespace=\"$Namespace\"}[$__rate_interval])",
       "legendFormat": "error",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "WARN logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"warn\", namespace=\"$Namespace\"}[$__rate_interval])",
       "legendFormat": "warn",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "DEBUG logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"debug\", namespace=\"$Namespace\"}[$__rate_interval])",
       "legendFormat": "debug",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "TRACE logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"trace\", namespace=\"$Namespace\"}[$__rate_interval])",
       "legendFormat": "trace",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    }
   ]
  }
 ]
}