version: '3.8'

services:

  internal-lb:
    image: nginx:latest
    network_mode: "host"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always

  account:
    image: "674959984960.dkr.ecr.ap-northeast-2.amazonaws.com/hejhome-pro:account-${ACCOUNT_VERSION}"
    pull_policy: always
    network_mode: "host"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - VERSION=${ACCOUNT_VERSION}

  device:
    image: "674959984960.dkr.ecr.ap-northeast-2.amazonaws.com/hejhome-pro:device-${DEVICE_VERSION}"
    pull_policy: always
    network_mode: "host"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - VERSION=${DEVICE_VERSION}

  notification:
    image: "674959984960.dkr.ecr.ap-northeast-2.amazonaws.com/hejhome-pro:notification-${NOTIFICATION_VERSION}"
    pull_policy: always
    network_mode: "host"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - VERSION=${NOTIFICATION_VERSION}

  event:
    image: "674959984960.dkr.ecr.ap-northeast-2.amazonaws.com/hejhome-pro:event-${EVENT_VERSION}"
    pull_policy: always
    network_mode: "host"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - VERSION=${EVENT_VERSION}
