services:
  config:
    image: "674959984960.dkr.ecr.ap-northeast-2.amazonaws.com/hejhome-pro:config-latest"
    pull_policy: always
    network_mode: "host"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - VERSION=1.0.0
    volumes:
      - /disk-A/logs/hejpro/config:/logs/config

  account:
    image: "674959984960.dkr.ecr.ap-northeast-2.amazonaws.com/hejhome-pro:account-latest"
    pull_policy: always
    network_mode: "host"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - VERSION=1.0.0
    volumes:
      - /disk-A/logs/hejpro/account:/logs/account

  device:
    image: "674959984960.dkr.ecr.ap-northeast-2.amazonaws.com/hejhome-pro:device-latest"
    pull_policy: always
    network_mode: "host"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - VERSION=1.0.0
    volumes:
      - /disk-A/logs/hejpro/device:/logs/device

  event:
    image: "674959984960.dkr.ecr.ap-northeast-2.amazonaws.com/hejhome-pro:event-latest"
    pull_policy: always
    network_mode: "host"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - VERSION=1.0.0
    volumes:
      - /disk-A/logs/hejpro/event:/logs/event

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8856:8080"
    environment:
      - SWAGGER_JSON=/files/merged.json
    volumes:
      - ./apidocs/files:/files