version: '3.8'

services:

  internal-lb:
    image: nginx:latest
    network_mode: "host"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always

  account:
    image: "674959984960.dkr.ecr.ap-northeast-2.amazonaws.com/hejhome-pro:account-1.0.22"
    pull_policy: always
    network_mode: "host"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - VERSION=1.0.22

  device:
    image: "674959984960.dkr.ecr.ap-northeast-2.amazonaws.com/hejhome-pro:device-1.0.30"
    pull_policy: always
    network_mode: "host"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - VERSION=1.0.30

  notification:
    image: "674959984960.dkr.ecr.ap-northeast-2.amazonaws.com/hejhome-pro:notification-1.0.14"
    pull_policy: always
    network_mode: "host"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - VERSION=1.0.14

  event:
    image: "674959984960.dkr.ecr.ap-northeast-2.amazonaws.com/hejhome-pro:event-1.0.19"
    pull_policy: always
    network_mode: "host"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - VERSION=1.0.19
