global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'account-actuator'
    metrics_path: /api/account/actuator/prometheus
    static_configs:
      - targets: ['localhost:8851']
        labels:
          application: "account"

  - job_name: 'device-actuator'
    metrics_path: /api/device/actuator/prometheus
    static_configs:
      - targets: ['localhost:8852']
        labels:
          application: "device"

  - job_name: 'event-actuator'
    metrics_path: /api/event/actuator/prometheus
    static_configs:
      - targets: ['localhost:8855']
        labels:
          application: "event"

