version: '3.8'

services:
  mongodb-hhp:
    image: mongo:7
    restart: always
    ports:
      - "8871:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - /disk-A/data/mongodb:/data/db

  mysql-hhp:
    image: mysql:8.0
    restart: always
    ports:
      - "8872:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - /disk-A/data/mysql:/var/lib/mysql

  redis-hhp:
    image: redis:7
    restart: always
    ports:
      - "8873:6379"
    command: ["redis-server", "--requirepass", "admin"]
    volumes:
      - /disk-A/data/redis:/data

  mosquitto-hhp:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "8875:1883"
    volumes:
      - /disk-A/data/mosquitto/data:/mosquitto/data
      - /disk-A/data/mosquitto/log:/mosquitto/log